backend:
  name: git-gateway
  branch: main
media_folder: public/assets
public_folder: /assets
collections:
  - name: pages
    label: Pages
    format: yaml-frontmatter
    files:
      - name: about_us
        label: About Us
        file: src/about-us.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: board_of_directors
        label: Board of Directors
        file: src/board-of-directors.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: committees
        label: Committees
        file: src/committees.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: contact_us
        label: Contact Us
        file: src/contact-us.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: faq
        label: FAQ
        file: src/faq.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: home
        label: Homepage
        file: src/index.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: our_community
        label: Our Community
        file: src/our-community.njk
        fields:
          - { name: title, label: Title, widget: string }
  - name: settings
    label: Settings
    format: yaml-frontmatter
    files:
      - name: navigation
        label: Navigation
        file: src/_includes/base.njk
        fields:
          - name: nav_items
            label: Navigation
            widget: list
            fields:
              - { name: label, label: Label, widget: string }
              - { name: path, label: Path, widget: string }
