backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: public/assets
public_folder: /assets
collections:
  - name: pages
    label: Pages
    folder: src/pages
    create: true
    slug: '{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - name: modules
        label: Modules
        widget: list
        types:
          - name: 'newsletter_signup'
            label: 'Newsletter Signup'
            widget: object
            fields:
              - { name: title, label: Title, widget: string, required: false, default: 'Sign up for our newsletter' }
              - { name: description, label: Description, widget: string, required: false }
              - { name: image, label: Image, widget: image, required: false }
          - name: 'call_out_grid'
            label: 'Callout Grid'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'accordion'
            label: 'Accordion'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'hero'
            label: 'Hero'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'image_card'
            label: 'Image Card'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'cta_card'
            label: 'CTA Card'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'cta_button'
            label: 'CTA Button'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'rich_text'
            label: 'Rich Text'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'image'
            label: 'Image'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
          - name: 'two_column_container'
            label: 'Container (2 Column)'
            widget: object
            fields:
              - { name: title, label: Title, widget: string }
              - name: 'left_column'
                label: 'Left Column'
                widget: object
                fields:
                  - { name: title, label: Title, widget: string }
                  - name: modules
                    label: Modules
                    widget: list
                    types:
                      - name: 'todo'
                        label: 'TODO'
                        widget: object
                        fields:
                          - { name: title, label: Title, widget: string }
              - name: 'right_column'
                label: 'Right Column'
                widget: object
                fields:
                  - { name: title, label: Title, widget: string }
                  - name: modules
                    label: Modules
                    widget: list
                    types:
                      - name: 'todo'
                        label: 'TODO'
                        widget: object
                        fields:
                          - { name: title, label: Title, widget: string }
  - name: one-off-pages
    label: One Off Pages
    format: yaml-frontmatter
    files:
      - name: about_us
        label: About Us
        file: src/about-us.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: board_of_directors
        label: Board of Directors
        file: src/board-of-directors.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: committees
        label: Committees
        file: src/committees.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: contact_us
        label: Contact Us
        file: src/contact-us.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: faq
        label: FAQ
        file: src/faq.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: home
        label: Homepage
        file: src/index.njk
        fields:
          - { name: title, label: Title, widget: string }
      - name: our_community
        label: Our Community
        file: src/our-community.njk
        fields:
          - { name: title, label: Title, widget: string }
  - name: settings
    label: Settings
    format: yaml-frontmatter
    files:
      - name: navigation
        label: Navigation
        file: src/_includes/base.njk
        fields:
          - name: nav_items
            label: Navigation
            widget: list
            fields:
              - { name: label, label: Label, widget: string }
              - { name: path, label: Path, widget: string }
              - name: sub_nav_items
                label: Sub Navigation
                widget: list
                fields:
                  - { name: label, label: Label, widget: string }
                  - { name: path, label: Path, widget: string }
