backend:
  name: git-gateway
  branch: main
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "pages"
    label: "Pages"
    format: "yaml-frontmatter"
    files:
      - name: "about-us"
        label: "About Us"
        file: "src/about-us.njk"
        fields:
          - { name: title, label: Title, widget: string }
